spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/account_bank
    username: user
    password: passpass
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 11000
logging:
  level:
    org.springframework.security.web.csrf: DEBUG