version: '3.8'
services:
  account-db:
    container_name: AppointmentHospital_account_
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account
      MYSQL_USER: user
      MYSQL_PASSWORD: passpass
volumes:
  db:
    driver: local
  cache:
      driver: local